quarkus:
  rest-client:
    datario-api:
      url: ${REST_CLIENT_API_BUS:https://dados.mobilidade.rio}
      enable-compression: true

  datasource:
    db-kind: postgresql
    username: ${QUARKUS_DATASOURCE_USERNAME:postgres}
    password: ${QUARKUS_DATASOURCE_PASSWORD:1234}
    jdbc:
      url: ${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://${CONEXAO_BD}:5433/postgres}
      statement-batch-size: 50
      max-lifetime: 1800s

  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
  transaction-manager:
    default-transaction-timeout: 3600s

riobus:
  geo:
    raio-terra-km: 6371
  api:
    limite-onibus: 5
    intervalo-cache: "60s"