quarkus:
  rest-client:
    datario-api:
      url: ${API_DATARIO_URL:https://dados.mobilidade.rio}
      enable-compression: true

  datasource:
    db-kind: postgresql
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}
    jdbc:
      url: ${DB_URL:jdbc:postgresql://localhost:5432/riobus}
      statement-batch-size: 50
      max-lifetime: 1800s

  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
  transaction-manager:
    default-transaction-timeout: 3600s

riobus:
  geo:
    raio-terra-km: 6371
  api:
    limite-onibus: 5
    intervalo-cache: "60s"