name: 'Automated Platform Deploy'

on:
  push:
    branches:
      - 'main'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout do Código'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Autenticação no GCP (WIF)'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ vars.GCP_WIF_PROVIDER }}'
          service_account: '${{ vars.GCP_SA_EMAIL }}'

      - name: 'Configurar Login do Docker no Artifact Registry'
        run: |-
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: 'Build e Push da Imagem Docker'
        run: |-
          # Monta a URL completa da imagem usando a variável APP_NAME
          IMAGE_URL="${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REPO }}/${{ vars.APP_NAME }}:${{ github.sha }}"
          
          # Ignorando os testes no CI/CD por enquanto (como conversamos antes)
          mvn clean package -DskipTests
          
          # Constrói o container lendo o seu Dockerfile local
          docker build -t $IMAGE_URL .
          
          # Envia a imagem para o Google Cloud Artifact Registry
          docker push $IMAGE_URL

      - name: 'Deploy no Cloud Run'
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ vars.APP_NAME }}'
          region: '${{ vars.GCP_REGION }}'
          image: '${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REPO }}/${{ vars.APP_NAME }}:${{ github.sha }}'
          # A MÁGICA DA REDE ACONTECE AQUI: Libera internet e conecta na sua VPC privada!
          # ATENÇÃO: Substitua 'subnet-us-central1' pelo nome exato da sub-rede que você criou.
          flags: '--allow-unauthenticated --network=apps-vpc --subnet=subnet-us-central1 --vpc-egress=private-ranges-only'
          # A MÁGICA DO 12-FACTOR APP (Variáveis de Ambiente):
          env_vars: |-
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_URL=jdbc:postgresql://${{ secrets.DB_INTERNAL_IP }}:5432/riobus
            DB_GENERATION=none
            LOG_SQL=false

      - name: 'Sucesso'
        run: |-
          echo "Seu backend subiu com sucesso!"
          echo "A URL pública (seu Gateway nativo) é: ${{ steps.deploy.outputs.url }}"